#!/bin/bash

set -x

###############################################################################
# run_fire.sh
#   Batch running script for executing fire on a worker node and then copying
#   the results to an output directory.
###############################################################################

_work_dir=$1 # directory to run inside of, should be in /export/scratch/users/$USER/
_env_script=$2 #environment to use
_config_script=$3 #script itself to run, should be in output directory
_output_dir=$4 #output directory to copy products to, should be in /hdfs/cms/user/$USER/ldmx/
_config_args=${@:5} #arguments to configuration script, input files should be in /hdfs/cms/user/$USER/ldmx/

if [[ ! -d /cvmfs/cms.cern.ch || ! -d /hdfs/cms/user ]]
then
  echo "Worker node is not connected to cvmfs and/or hdfs."
  exit 99
fi

if ! mkdir -p $_work_dir
then
  echo "Can't create working directory."
  exit 110
fi
cd $_work_dir

if [[ ! -z "$(ls -A .)" ]]
then
  # temp directory non-empty
  #   we need to clean it before running so that
  #   the only files are the ones generated by
  #   our run of fire
  rm -r *
fi

if ! source $_env_script
then
  echo "Wasn't able to source the environment script."
  exit 111
fi

if ! fire $_config_script $_config_args
then
  echo "fire returned an non-zero error status."
  exit 115
fi

# mv all output root files to the output directory
if ! mv *.root $_output_dir
then
  echo "Can't copy the output root files to the output directory (or couldn't find output files)."
  exit 117
fi
